version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts

commands:
  setup_dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: build
          paths:
            - "*"

  test:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies
      - run: # run tests
          name: Test
          command: npm test
      # - run:
      #     name: "Run Jest and Collect Coverage Reports"
      #     command: jest --collectCoverage=true
      # - store_artifacts:
      #     path: coverage
      #     previx: coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

  deploy:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies
      - run:
          name: Install gh-pages
          command: npm install gh-pages
      - run:
          name: Setup Git Configs
          command: |
            git config user.email "build@circleci.com"
            git config user.name "circleci-build"
      - attach_workspace:
          at: build
      - add_ssh_keys:
          fingerprints:
            - "b5:3b:e4:44:28:54:fc:60:3f:a3:19:63:f3:3d:5c:7a"
      - run:
          name: Deploy
          command: ./node_modules/.bin/gh-pages --message "[skip ci] Updates" --dist build

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
