version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts

commands:
  setup_dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  setup_dependencies_deploy:
    steps:
      - restore_cache:
          key: dependency-cache-deploy-{{ checksum "package.json" }}
      - run:
          name: Install gh-pages
          command: npm install gh-pages
      - save_cache:
          key: dependency-cache-deploy-{{ checksum "package.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: build
          paths:
            - "*"

  test:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies
      - run:
          name: Test
          command: npm test

  deploy:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - setup_dependencies_deploy
      - run:
          name: Setup Git Configs
          command: |
            git config user.email "build@circleci.com"
            git config user.name "circleci-build"
      - attach_workspace:
          at: build
      - add_ssh_keys:
          fingerprints:
            - "b5:3b:e4:44:28:54:fc:60:3f:a3:19:63:f3:3d:5c:7a"
      - run:
          name: Deploy
          command: npx gh-pages --message "[skip ci] Updates" --dist build

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
